name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Outputs the name of the repository (owner/repo)
      - name: Build Image Name
        id: image
        run: |
          # The name of the owner and of the repository: owner/repository
          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=image_name::${IMAGE_NAME}

      # Outputs container tags for tagged pushes starting by 'v'
      # Pushes only to GitHub Container Repository (ghcr.io)
      #
      # Tags stable versions as :latest
      # Pre-releases, alphas, etc. as :snapshot
      - name: Prepare Image Tags from Git Tag
        id: tagged
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          # Remove everything else than the tagged version
          VERSION=${GITHUB_REF#refs/tags/v}

          # Tag as stable (:latest) if there is no letters in the version
          # Otherwise, tag as preview (:snapshot)
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            # Matches v1.0.0, v1.0.1, etc.
            NAMED_VERSION="latest"
          else
            # Matches v1.0.0a1, v1.0.0rc1, etc.
            NAMED_VERSION="snapshot"
          fi

          TAGS=$"
          ghcr.io/${{ steps.image.outputs.image_name }}:latest,\
          ghcr.io/${{ steps.image.outputs.image_name }}:${VERSION}\
          "

          # Output the target tags
          echo -n "${TAGS}" > /tmp/container-tags

      # Outputs the containers tags for staging branches
      # Only publishes them onto Docker Hub
      - name: Prepare Tags for Staging
        id: staging
        if: ${{ startsWith(github.ref, 'refs/heads/v') }}
        run: |
          # Version name is the branch name
          NAMED_VERSION=${GITHUB_REF#refs/heads/}
          SHA=${GITHUB_SHA}

          # Target Docker Hub with the SHA value
          # and branch name
          TAGS=$"
          ${{ steps.image.outputs.image_name }}:${NAMED_VERSION},\
          ${{ steps.image.outputs.image_name }}:${SHA}\
          "

          # Output the target tags
          echo -n "${TAGS}" > /tmp/container-tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: $(cat /tmp/container-tags)
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: |
          echo $"\
            Digest: ${{ steps.docker_build.outputs.digest }}
            Tags: ${{ steps.tagged.outputs.tags }},${{ steps.staging.outputs.tags }}"
